environment:

  matrix:

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "64"
      PIP: "C:\\Python35-x64\\Scripts\\pip"

install:

  - cmd: "%PIP% install --disable-pip-version-check --user --upgrade pip"
  - cmd: "%PIP% install lxml"
  - cmd: "%PIP% install beautifulsoup4"
  - cmd: "%PIP% install w3lib"
  - cmd: "chcp 65001"

build_script:

  - cmd: "%PYTHON%\\python -u KristinitaLuckyLinkTest.py"