environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"
      UNICODE: ON

platform: x64

install:

  - cmd: "chcp 65001"

build_script:

  - cmd: "%PYTHON%\\python -u SashaAppVeyorEncoding.py"